"""Adcionando campo itens na classe Pedidos

Revision ID: 7add30f8bfe7
Revises: 4d70c8ef0b0b
Create Date: 2026-01-13 01:44:40.889257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7add30f8bfe7'
down_revision: Union[str, Sequence[str], None] = '4d70c8ef0b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
